category_groups:
  type: "list"
  default: "Default Categories: staff, site-feedback, lounge"
  description: "Format as: Group name: category-slug, category-slug-2"
  
category_headers:
  type: "list"
  default: "Default Categories;image;https://demo.shadowdevs.com/img/bg.jpg"
  description: "Add header information for the header to be enabled for designated category.<br>Format as: Group name;type(color or image);hex code or url"

show_on_mobile: 
  default: true
  description: "Show the collapsible category box groups on mobile"

show_ungrouped: 
  default: true
  description: "Display a group of categories that aren't assigned to another group"

fancy_styling: 
  default: false
  description: "Turn on additional styling"
